#!/usr/bin/env bash
# This script checks subdomain DNS A records using dig and awk

get_record() {
    local full_domain="$1"
    local sub="$2"
    result=$(dig "$full_domain" +short)

    if [ -n "$result" ]; then
        record_type="A"
        destination="$result"
        echo "The subdomain $sub is a $record_type record and points to $destination"
    else
        echo "No A record found for $full_domain"
    fi
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02; do
        get_record "${sub}.${domain}" "$sub"
    done
else
    get_record "${subdomain}.${domain}" "$subdomain"
fi

